-- Oracle Primary Key 구성 컬럼 확인
-- TABLE_NAME에 확인할 테이블명을 대문자로 입력

SELECT A.CONSTRAINT_NAME
     , A.CONSTRAINT_TYPE
     , B.COLUMN_NAME
     , B.POSITION
FROM USER_CONSTRAINTS A
     , USER_CONS_COLUMNS B
WHERE A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
AND A.TABLE_NAME = '테이블명'
AND A.CONSTRAINT_TYPE = 'P'
ORDER BY B.POSITION;

-- CONSTRAINT_TYPE
-- P : PRIMARY KEY
-- U : UNIQUE
-- R : FOREIGN KEY
